packages:
  - .
  - 'packages/*'
  - tapsss-forum

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  simple-git-hooks: true

shellEmulator: true
trustPolicy: audit
trustPolicyExclude:
  - semver@6.3.1
  - semver@5.7.2
