packages:
  - .
  - 'packages/*'
  - tapsss-forum
  - bar_chart_race

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  simple-git-hooks: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - semver@5.7.2
