name: CI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Get version
        id: get_version
        shell: bash
        run: |
          echo "version=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: set .env
        run: |
          echo "ENCRYPT_KEY=${{ secrets.ENCRYPT_KEY }}" > .env
          echo "ENCRYPT_SALT=${{ secrets.ENCRYPT_SALT }}" >> .env
          echo "ENCRYPT_SECRET_KEY=${{ secrets.ENCRYPT_SECRET_KEY }}" >> .env
          echo "DECRYPT_SECRET_KEY=${{ secrets.DECRYPT_SECRET_KEY }}" >> .env

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.5

      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build render & main
        run: pnpm run build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/v${{ env.version }}/*.exe
            release/v${{ env.version }}/*.blockmap
          name: 'Mines Client Lite ${{ env.version }}'
